package com.example.util

data class AppStrings(
    val language: AppLanguage,
    
    // Bottom Navigation
    val navHome: String,
    val navTransactions: String,
    val navInvoices: String,
    val navReports: String,
    val navProfile: String,
    
    // Dashboard Screen
    val greeting: String,
    val manageBusiness: String,
    val totalBalance: String,
    val totalIncome: String,
    val totalExpenses: String,
    val pendingPayments: String,
    val monthlyRevenue: String,
    val monthlyExpenses: String,
    val quickActions: String,
    val addIncome: String,
    val addExpense: String,
    val createInvoice: String,
    val addCustomer: String,
    val quickHub: String,
    val customers: String,
    val suppliers: String,
    val products: String,
    val reminders: String,
    val recentTransactions: String,
    val recentInvoices: String,
    val viewAll: String,
    val noTransactionsYet: String,
    val noInvoicesYet: String,
    val switchLanguage: String,

    // Transactions Screen
    val transactionsTitle: String,
    val all: String,
    val income: String,
    val expense: String,
    val searchTransactionsHint: String,
    val newIncomeTitle: String,
    val newExpenseTitle: String,
    val editTransactionTitle: String,
    val deleteTransactionTitle: String,
    val deleteTransactionConfirm: String,
    val amountLabel: String,
    val categoryLabel: String,
    val dateLabel: String,
    val notesLabel: String,
    val paymentMethodLabel: String,
    val partyNameLabel: String,
    val referenceLabel: String,
    val saveButton: String,
    val cancelButton: String,
    val deleteButton: String,
    val editButton: String,

    // Categories
    val catFood: String,
    val catShopping: String,
    val catTransport: String,
    val catSalary: String,
    val catBusiness: String,
    val catBills: String,
    val catRent: String,
    val catMarketing: String,
    val catOther: String,

    // Payment Methods
    val payBankTransfer: String,
    val payCash: String,
    val payUpiCard: String,
    val payCheque: String,
    val payOnline: String,

    // Invoices Screen
    val invoicesTitle: String,
    val statusPaid: String,
    val statusPending: String,
    val statusOverdue: String,
    val searchInvoicesHint: String,
    val createNewInvoice: String,
    val invoiceNumber: String,
    val customerLabel: String,
    val invoiceDate: String,
    val dueDate: String,
    val itemsLabel: String,
    val quantityLabel: String,
    val priceLabel: String,
    val discountLabel: String,
    val taxLabel: String,
    val subtotalLabel: String,
    val totalLabel: String,
    val paymentStatusLabel: String,
    val paidAmountLabel: String,
    val remainingAmountLabel: String,
    val generatePdfButton: String,
    val shareInvoiceButton: String,
    val shareWhatsAppButton: String,
    val markAsPaidButton: String,
    val recordPaymentButton: String,
    val invoiceDetailsTitle: String,

    // Reports Screen
    val reportsTitle: String,
    val filterThisWeek: String,
    val filterThisMonth: String,
    val filterLastMonth: String,
    val filterThisYear: String,
    val netProfit: String,
    val incomeVsExpense: String,
    val monthlyRevenueTrend: String,
    val expenseByCategory: String,
    val pendingSummary: String,
    val receivablesLabel: String,
    val payablesLabel: String,

    // Customers, Suppliers, Products
    val customersTitle: String,
    val suppliersTitle: String,
    val productsTitle: String,
    val remindersTitle: String,
    val searchCustomersHint: String,
    val searchSuppliersHint: String,
    val searchProductsHint: String,
    val newCustomer: String,
    val newSupplier: String,
    val newProduct: String,
    val phoneLabel: String,
    val emailLabel: String,
    val addressLabel: String,
    val skuLabel: String,
    val inStockLabel: String,
    val lowStockLabel: String,

    // Profile & Settings
    val profileTitle: String,
    val businessInfoSection: String,
    val editBusinessInfo: String,
    val businessNameLabel: String,
    val businessPhoneLabel: String,
    val businessEmailLabel: String,
    val businessAddressLabel: String,
    val businessTaxIdLabel: String,
    val languageSection: String,
    val appLanguageLabel: String,
    val selectLanguageTitle: String,
    val regionDefaultsSection: String,
    val currencySymbolLabel: String,
    val defaultTaxRateLabel: String,
    val securityPreferencesSection: String,
    val pinProtectionLabel: String,
    val pinProtectionSub: String,
    val changePinLabel: String,
    val darkThemeLabel: String,
    val notificationsLabel: String,
    val logoutLabel: String,
    val logoutConfirmMessage: String,

    // AI Features
    val aiHubTitle: String,
    val aiHubSubtitle: String,
    val aiScanBill: String,
    val aiVoiceEntry: String,
    val aiAdvisor: String,
    val aiScanningBillTitle: String,
    val aiScanningBillSubtitle: String,
    val aiVoiceDialogTitle: String,
    val aiVoiceListening: String,
    val aiVoiceHint: String,
    val aiParseButton: String,
    val aiAdvisorTitle: String,
    val aiAdvisorSubtitle: String,
    val aiRefreshAdvice: String,
    val aiWhatsAppReminderTitle: String,
    val aiGenerateReminder: String,
    val aiReminderTonePolite: String,
    val aiReminderToneProfessional: String,
    val aiReminderToneUrgent: String,
    val aiSendWhatsApp: String,
    val aiExtractedDetails: String,
    val aiSaveToLedger: String,
    val aiSelectPhoto: String,
    val aiTakePhoto: String,
    val aiEmptyVoicePrompt: String,
    val aiSuccessEntrySaved: String
) {
    fun category(name: String): String {
        return when (name.trim().lowercase()) {
            "food" -> catFood
            "shopping" -> catShopping
            "transport" -> catTransport
            "salary" -> catSalary
            "business" -> catBusiness
            "bills" -> catBills
            "rent" -> catRent
            "marketing" -> catMarketing
            else -> if (name.isNotBlank()) name else catOther
        }
    }

    fun status(status: String): String {
        return when (status.uppercase()) {
            "PAID" -> statusPaid
            "PENDING" -> statusPending
            "OVERDUE" -> statusOverdue
            else -> status
        }
    }

    fun paymentMethod(method: String): String {
        return when (method.trim().lowercase()) {
            "bank transfer" -> payBankTransfer
            "cash" -> payCash
            "upi / card", "upi", "card" -> payUpiCard
            "cheque" -> payCheque
            "online" -> payOnline
            else -> method
        }
    }

    companion object {
        fun get(language: AppLanguage): AppStrings {
            return when (language) {
                AppLanguage.GUJARATI -> GujaratiStrings
                AppLanguage.ENGLISH -> EnglishStrings
            }
        }
    }
}

val EnglishStrings = AppStrings(
    language = AppLanguage.ENGLISH,
    navHome = "Home",
    navTransactions = "Transactions",
    navInvoices = "Invoices",
    navReports = "Reports",
    navProfile = "Profile",
    
    greeting = "Good day,",
    manageBusiness = "Manage your money & business",
    totalBalance = "Total Balance",
    totalIncome = "Total Income",
    totalExpenses = "Total Expenses",
    pendingPayments = "Pending Payments",
    monthlyRevenue = "Monthly Revenue",
    monthlyExpenses = "Monthly Expenses",
    quickActions = "Quick Actions",
    addIncome = "Add Income",
    addExpense = "Add Expense",
    createInvoice = "Create Invoice",
    addCustomer = "Add Customer",
    quickHub = "Business Hub",
    customers = "Customers",
    suppliers = "Suppliers",
    products = "Products",
    reminders = "Reminders",
    recentTransactions = "Recent Transactions",
    recentInvoices = "Recent Invoices",
    viewAll = "View All",
    noTransactionsYet = "No transactions recorded yet",
    noInvoicesYet = "No invoices created yet",
    switchLanguage = "Switch Language",

    transactionsTitle = "Transactions",
    all = "All",
    income = "Income",
    expense = "Expense",
    searchTransactionsHint = "Search transactions...",
    newIncomeTitle = "New Income",
    newExpenseTitle = "New Expense",
    editTransactionTitle = "Edit Transaction",
    deleteTransactionTitle = "Delete Transaction",
    deleteTransactionConfirm = "Are you sure you want to delete this transaction?",
    amountLabel = "Amount",
    categoryLabel = "Category",
    dateLabel = "Date",
    notesLabel = "Notes",
    paymentMethodLabel = "Payment Method",
    partyNameLabel = "Customer / Party Name",
    referenceLabel = "Invoice / Reference ID",
    saveButton = "Save",
    cancelButton = "Cancel",
    deleteButton = "Delete",
    editButton = "Edit",

    catFood = "Food & Dining",
    catShopping = "Shopping & Supplies",
    catTransport = "Travel & Transport",
    catSalary = "Salary & Payroll",
    catBusiness = "Business Sales",
    catBills = "Bills & Utilities",
    catRent = "Office Rent",
    catMarketing = "Ads & Marketing",
    catOther = "Other Expenses",

    payBankTransfer = "Bank Transfer",
    payCash = "Cash",
    payUpiCard = "UPI / Card",
    payCheque = "Cheque",
    payOnline = "Online Payment",

    invoicesTitle = "Invoices & Billing",
    statusPaid = "Paid",
    statusPending = "Pending",
    statusOverdue = "Overdue",
    searchInvoicesHint = "Search invoices, customers...",
    createNewInvoice = "Create New Invoice",
    invoiceNumber = "Invoice #",
    customerLabel = "Customer",
    invoiceDate = "Invoice Date",
    dueDate = "Due Date",
    itemsLabel = "Line Items",
    quantityLabel = "Qty",
    priceLabel = "Price",
    discountLabel = "Discount",
    taxLabel = "Tax / GST",
    subtotalLabel = "Subtotal",
    totalLabel = "Total Amount",
    paymentStatusLabel = "Payment Status",
    paidAmountLabel = "Paid Amount",
    remainingAmountLabel = "Remaining Due",
    generatePdfButton = "Generate PDF",
    shareInvoiceButton = "Share Invoice",
    shareWhatsAppButton = "Send on WhatsApp",
    markAsPaidButton = "Mark as Paid",
    recordPaymentButton = "Record Partial Payment",
    invoiceDetailsTitle = "Invoice Details",

    reportsTitle = "Financial Reports & Analytics",
    filterThisWeek = "This Week",
    filterThisMonth = "This Month",
    filterLastMonth = "Last Month",
    filterThisYear = "This Year",
    netProfit = "Net Profit",
    incomeVsExpense = "Income vs Expense Breakdown",
    monthlyRevenueTrend = "6-Month Revenue Trend",
    expenseByCategory = "Expenses by Category",
    pendingSummary = "Receivables & Payables Summary",
    receivablesLabel = "Customer Receivables",
    payablesLabel = "Supplier Payables",

    customersTitle = "Customer Directory",
    suppliersTitle = "Supplier Directory",
    productsTitle = "Products & Inventory",
    remindersTitle = "Payment Reminders",
    searchCustomersHint = "Search by customer name, phone...",
    searchSuppliersHint = "Search by supplier or company...",
    searchProductsHint = "Search product name or SKU...",
    newCustomer = "Add Customer",
    newSupplier = "Add Supplier",
    newProduct = "Add Product",
    phoneLabel = "Phone",
    emailLabel = "Email",
    addressLabel = "Address",
    skuLabel = "SKU",
    inStockLabel = "In Stock",
    lowStockLabel = "Low Stock",

    profileTitle = "Profile & Settings",
    businessInfoSection = "Business Information",
    editBusinessInfo = "Edit Company Details",
    businessNameLabel = "Company / Business Name",
    businessPhoneLabel = "Phone Number",
    businessEmailLabel = "Billing Email",
    businessAddressLabel = "Office Address",
    businessTaxIdLabel = "Tax / GST Number",
    languageSection = "Language & Region",
    appLanguageLabel = "App Language",
    selectLanguageTitle = "Choose App Language",
    regionDefaultsSection = "Financial & Region Defaults",
    currencySymbolLabel = "Currency Symbol",
    defaultTaxRateLabel = "Default Tax Rate",
    securityPreferencesSection = "Security & Preferences",
    pinProtectionLabel = "4-Digit PIN Protection",
    pinProtectionSub = "Require PIN code to open ledger",
    changePinLabel = "Change PIN Code",
    darkThemeLabel = "Dark Appearance",
    notificationsLabel = "Payment Due Alerts",
    logoutLabel = "Log Out of Account",
    logoutConfirmMessage = "Are you sure you want to sign out?",

    aiHubTitle = "✨ MyLedger AI Assistant",
    aiHubSubtitle = "Smart Bill Scanner, Voice Entry & CA Insights",
    aiScanBill = "Scan Bill",
    aiVoiceEntry = "Voice Entry",
    aiAdvisor = "Business Advice",
    aiScanningBillTitle = "Scanning Bill with AI...",
    aiScanningBillSubtitle = "Extracting total amount, party, date & items",
    aiVoiceDialogTitle = "AI Voice / Smart Entry",
    aiVoiceListening = "Listening... Speak in Gujarati or English",
    aiVoiceHint = "e.g. 'Received 500 from Ramesh' or 'Paid shop rent 12000 cash'",
    aiParseButton = "Process with AI",
    aiAdvisorTitle = "✨ AI Business Advisor",
    aiAdvisorSubtitle = "Smart financial audit & cashflow tips by Gemini",
    aiRefreshAdvice = "Re-analyze Ledger",
    aiWhatsAppReminderTitle = "AI WhatsApp Reminder",
    aiGenerateReminder = "Generate Message",
    aiReminderTonePolite = "Polite & Friendly",
    aiReminderToneProfessional = "Professional",
    aiReminderToneUrgent = "Urgent Collection",
    aiSendWhatsApp = "Send on WhatsApp",
    aiExtractedDetails = "AI Extracted Details",
    aiSaveToLedger = "Save to Khata",
    aiSelectPhoto = "Choose Bill Photo",
    aiTakePhoto = "Take Photo",
    aiEmptyVoicePrompt = "Please speak or enter transaction details first",
    aiSuccessEntrySaved = "Transaction saved to ledger successfully!"
)

val GujaratiStrings = AppStrings(
    language = AppLanguage.GUJARATI,
    navHome = "ડેશબોર્ડ",
    navTransactions = "વ્યવહારો",
    navInvoices = "બિલ / ઇનવોઇસ",
    navReports = "અહેવાલ",
    navProfile = "સેટિંગ્સ",

    greeting = "નમસ્તે,",
    manageBusiness = "તમારા નાણાં અને વેપારનું સરળ સંચાલન",
    totalBalance = "કુલ સિલક (બેલેન્સ)",
    totalIncome = "કુલ આવક",
    totalExpenses = "કુલ ખર્ચ",
    pendingPayments = "બાકી ઉઘરાણી",
    monthlyRevenue = "માસિક આવક",
    monthlyExpenses = "માસિક ખર્ચ",
    quickActions = "ઝડપી ક્રિયાઓ",
    addIncome = "આવક ઉમેરો",
    addExpense = "ખર્ચ ઉમેરો",
    createInvoice = "ઇનવોઇસ બનાવો",
    addCustomer = "ગ્રાહક ઉમેરો",
    quickHub = "બિઝનેસ હબ",
    customers = "ગ્રાહકો",
    suppliers = "વેપારીઓ",
    products = "પ્રોડક્ટ્સ",
    reminders = "યાદી / રીમાઇન્ડર",
    recentTransactions = "તાજેતરના વ્યવહારો",
    recentInvoices = "તાજેતરના બિલ",
    viewAll = "બધું જુઓ",
    noTransactionsYet = "હજુ સુધી કોઈ વ્યવહાર નોંધાયેલ નથી",
    noInvoicesYet = "હજુ સુધી કોઈ ઇનવોઇસ બનાવેલ નથી",
    switchLanguage = "ભાષા બદલો",

    transactionsTitle = "આવક અને ખર્ચ વ્યવહારો",
    all = "બધા",
    income = "આવક",
    expense = "ખર્ચ",
    searchTransactionsHint = "વ્યવહારો, નોંધ અથવા પક્ષકાર શોધો...",
    newIncomeTitle = "નવી આવક નોંધો",
    newExpenseTitle = "નવો ખર્ચ નોંધો",
    editTransactionTitle = "વ્યવહાર સુધારો",
    deleteTransactionTitle = "વ્યવહાર કાઢી નાખો",
    deleteTransactionConfirm = "શું તમે ખરેખર આ વ્યવહાર કાઢી નાખવા માંગો છો?",
    amountLabel = "રકમ (₹)",
    categoryLabel = "કેટેગરી",
    dateLabel = "તારીખ",
    notesLabel = "નોંધ / વિગત",
    paymentMethodLabel = "ચૂકવણી પદ્ધતિ",
    partyNameLabel = "ગ્રાહક / પક્ષકારનું નામ",
    referenceLabel = "ઇનવોઇસ અથવા સંદર્ભ નંબર",
    saveButton = "સાચવો",
    cancelButton = "રદ કરો",
    deleteButton = "કાઢી નાખો",
    editButton = "સુધારો",

    catFood = "ખોરાક અને ભોજન",
    catShopping = "સામાન અને ખરીદી",
    catTransport = "પરિવહન અને યાત્રા",
    catSalary = "પગાર અને મહેનતાણું",
    catBusiness = "વેપાર વેચાણ",
    catBills = "લાઈટ બિલ અને ખર્ચા",
    catRent = "દુકાન / ઓફિસ ભાડું",
    catMarketing = "જાહેરાત અને માર્કેટિંગ",
    catOther = "અન્ય ખર્ચ",

    payBankTransfer = "બેંક ટ્રાન્સફર",
    payCash = "રોકડ (કેશ)",
    payUpiCard = "UPI / કાર્ડ",
    payCheque = "ચેક",
    payOnline = "ઓનલાઇન પેમેન્ટ",

    invoicesTitle = "ઇનવોઇસ અને બિલિંગ",
    statusPaid = "ચૂકવેલ",
    statusPending = "બાકી",
    statusOverdue = "મુદત વીતેલ",
    searchInvoicesHint = "બિલ નંબર, ગ્રાહક શોધો...",
    createNewInvoice = "નવું ઇનવોઇસ બનાવો",
    invoiceNumber = "બિલ નંબર",
    customerLabel = "ગ્રાહકનું નામ",
    invoiceDate = "બિલ તારીખ",
    dueDate = "ચૂકવણીની છેલ્લી તારીખ",
    itemsLabel = "માલસામાન / સેવાઓ",
    quantityLabel = "જથ્થો",
    priceLabel = "ભાવ / દર",
    discountLabel = "વળતર (ડિસ્કાઉન્ટ)",
    taxLabel = "જીએસટી / ટેક્સ",
    subtotalLabel = "પેટા સરવાળો",
    totalLabel = "કુલ રકમ",
    paymentStatusLabel = "ચૂકવણીની સ્થિતિ",
    paidAmountLabel = "મળેલ રકમ",
    remainingAmountLabel = "બાકી નીકળતી રકમ",
    generatePdfButton = "PDF બિલ બનાવો",
    shareInvoiceButton = "બિલ મોકલો",
    shareWhatsAppButton = "વ્હોટ્સએપ પર મોકલો",
    markAsPaidButton = "ચૂકવેલ તરીકે નોંધો",
    recordPaymentButton = "આંશિક ચૂકવણી નોંધો",
    invoiceDetailsTitle = "ઇનવોઇસની વિગતો",

    reportsTitle = "નાણાકીય અહેવાલ અને એનાલિટિક્સ",
    filterThisWeek = "આ અઠવાડિયે",
    filterThisMonth = "આ મહિને",
    filterLastMonth = "ગયા મહિને",
    filterThisYear = "આ વર્ષે",
    netProfit = "ચોખ્ખો નફો (Profit)",
    incomeVsExpense = "આવક અને ખર્ચની સરખામણી",
    monthlyRevenueTrend = "૬ મહિનાની આવકનો પ્રવાહ",
    expenseByCategory = "કેટેગરી મુજબ ખર્ચ વિશ્લેષણ",
    pendingSummary = "લેણી અને દેવી રકમનો સારાંશ",
    receivablesLabel = "ગ્રાહકો પાસેથી લેણી રકમ",
    payablesLabel = "વેપારીઓને ચૂકવવાપાત્ર રકમ",

    customersTitle = "ગ્રાહકોની યાદી",
    suppliersTitle = "સપ્લાયર્સ / વેપારીઓ",
    productsTitle = "માલ-સામાન અને સ્ટોક",
    remindersTitle = "બાકી ઉઘરાણી યાદી",
    searchCustomersHint = "ગ્રાહકનું નામ અથવા મોબાઈલ શોધો...",
    searchSuppliersHint = "વેપારી અથવા કંપની શોધો...",
    searchProductsHint = "પ્રોડક્ટનું નામ અથવા SKU શોધો...",
    newCustomer = "નવો ગ્રાહક ઉમેરો",
    newSupplier = "નવા વેપારી ઉમેરો",
    newProduct = "નવો માલ ઉમેરો",
    phoneLabel = "મોબાઈલ નંબર",
    emailLabel = "ઇમેઇલ",
    addressLabel = "સરનામું",
    skuLabel = "કોડ / SKU",
    inStockLabel = "સ્ટોકમાં ઉપલબ્ધ",
    lowStockLabel = "ઓછો સ્ટોક",

    profileTitle = "પ્રોફાઇલ અને સેટિંગ્સ",
    businessInfoSection = "પેઢી / વેપારની માહિતી",
    editBusinessInfo = "પેઢીની વિગત સુધારો",
    businessNameLabel = "પેઢી / દુકાનનું નામ",
    businessPhoneLabel = "સંપર્ક નંબર",
    businessEmailLabel = "બિલિંગ ઇમેઇલ",
    businessAddressLabel = "ઓફિસ / દુકાનનું સરનામું",
    businessTaxIdLabel = "જીએસટી / પાન નંબર",
    languageSection = "ભાષા અને પ્રાંત પસંદગી",
    appLanguageLabel = "એપની ભાષા (App Language)",
    selectLanguageTitle = "એપની ભાષા પસંદ કરો",
    regionDefaultsSection = "નાણાકીય અને ચલણ સેટિંગ્સ",
    currencySymbolLabel = "ચલણ ચિહ્ન (Currency)",
    defaultTaxRateLabel = "સામાન્ય ટેક્સ દર (%)",
    securityPreferencesSection = "સુરક્ષા અને દેખાવ",
    pinProtectionLabel = "૪-અંક પિન સુરક્ષા",
    pinProtectionSub = "એપ ખોલવા માટે પિન કોડ ફરજિયાત કરો",
    changePinLabel = "પિન કોડ બદલો",
    darkThemeLabel = "ડાર્ક મોડ (Dark Appearance)",
    notificationsLabel = "ચૂકવણી બાકી એલર્ટ્સ",
    logoutLabel = "ખાતામાંથી બહાર નીકળો (લૉગ આઉટ)",
    logoutConfirmMessage = "શું તમે ખરેખર લૉગ આઉટ કરવા માંગો છો?",

    aiHubTitle = "✨ માયલેજર AI સહાયક",
    aiHubSubtitle = "સ્માર્ટ બિલ સ્કેનર, બોલીને એન્ટ્રી અને બિઝનેસ સલાહ",
    aiScanBill = "બિલ સ્કેન કરો",
    aiVoiceEntry = "બોલીને એન્ટ્રી",
    aiAdvisor = "બિઝનેસ સલાહ",
    aiScanningBillTitle = "AI બિલ વાંચી રહ્યું છે...",
    aiScanningBillSubtitle = "રકમ, વેપારીનું નામ, તારીખ અને વિગતો શોધી રહ્યું છે",
    aiVoiceDialogTitle = "AI બોલીને ખાતાવહી એન્ટ્રી",
    aiVoiceListening = "સાંભળી રહ્યું છે... ગુજરાતી કે English માં બોલો",
    aiVoiceHint = "દા.ત. 'રમેશભાઈ પાસેથી ૫૦૦ મળ્યા' અથવા 'દુકાન ભાડું ૧૨૦૦૦ રોકડા ચૂકવ્યું'",
    aiParseButton = "AI થી એન્ટ્રી બનાવો",
    aiAdvisorTitle = "✨ AI બિઝનેસ સલાહકાર",
    aiAdvisorSubtitle = "જેમિનાઈ AI દ્વારા તમારા વ્યવસાયનું સ્માર્ટ ઓડિટ",
    aiRefreshAdvice = "નવેસરથી એનાલિસિસ કરો",
    aiWhatsAppReminderTitle = "AI વ્હોટ્સએપ રીમાઇન્ડર",
    aiGenerateReminder = "મેસેજ તૈયાર કરો",
    aiReminderTonePolite = "નમ્ર અને સ્નેહભર્યો",
    aiReminderToneProfessional = "વ્યાપારી (Professional)",
    aiReminderToneUrgent = "તાત્કાલિક ઉઘરાણી",
    aiSendWhatsApp = "વ્હોટ્સએપ પર મોકલો",
    aiExtractedDetails = "AI દ્વારા શોધાયેલી વિગતો",
    aiSaveToLedger = "ખાતામાં સેવ કરો",
    aiSelectPhoto = "બિલનો ફોટો પસંદ કરો",
    aiTakePhoto = "કેમેરાથી ફોટો લો",
    aiEmptyVoicePrompt = "કૃપા કરીને પહેલા કંઈક બોલો અથવા વિગત લખો",
    aiSuccessEntrySaved = "ટ્રાન્ઝેક્શન સફળતાપૂર્વક ખાતામાં સેવ થઈ ગયું!"
)
